# 应用名称
spring:
  application:
    name: seata-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn-seata-order?userUnicode=true&characterEncoding=utf-8
    username: root
    password: root
server:
  port: 9901

seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: my_test_tx_group
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      username: nacos
      password: nacos
      namespace: seata
  service:
    vgroup-mapping:
      my_test_tx_group: default
    disable-global-transaction: false
  client:
    rm:
      report-success-enable: false

logging:
  level:
    root: debug
    com:
      alibaba:
        nacos: info
    sun:
      sun:
        rmi: info
      net:
        www: info
