# 应用名称
spring:
  application:
    name: seata-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn-seata-order?userUnicode=true&characterEncoding=utf-8
    username: root
    password: root
server:
  port: 9901

logging:
  level:
    root: debug
    com:
      alibaba:
        nacos: info
    sun:
      sun:
        rmi: info
      net:
        www: info
